name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches:
      - master
jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pobk.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pobk
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      
          plugin_achievements_secrets: yes      
          plugin_achievements_display: compact  
          plugin_achievements_limit: 0          

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pobk.header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pobk
          template: classic
          base: header

  acti_comm:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pobk.community.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pobk
          template: classic
          base: activity, community

  iso_calender:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pobk.iso_calender.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pobk
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pobk.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pobk
          base: ""
          template: classic
          plugin_habits: yes
          plugin_habits_from: 200       
          plugin_habits_days: 14        
          plugin_habits_charts: yes     
          plugin_habits_trim: yes       

  issue_pr_lang:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pobk.issue_pr_lang.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pobk
          template: classic
          base: ""
          plugin_followup: yes
          plugin_languages: yes

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pobk.repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pobk
          template: classic
          plugin_lines: yes
          base: repositories
